[general]
library_name = "libsuperlu_dist_Int64"
library_names = {"superlu_ddefs.h" = "libsuperlu_ddefs"}
prologue_file_path = "./prologue.jl"

use_julia_native_enum_type = true
use_deterministic_symbol = true
auto_mutability = false

output_ignorelist = [
    "FC_GLOBAL"

]

[codegen]
use_ccall_macro = true

[codegen.macro]
macro_mode = "basic"

functionlike_macro_includelist = [

]
