[general]
library_name = "libsuperlu_dist_Int64"
library_names = {"superlu_ddefs.h" = "libsuperlu_ddefs"}

use_julia_native_enum_type = true
use_deterministic_symbol = true
auto_mutability = true

output_ignorelist = [
    # Clang.jl cannot handle these macro correctly, skip for now.

    # useless macros

]

[codegen]
use_ccall_macro = true

[codegen.macro]
macro_mode = "basic"

functionlike_macro_includelist = [

]
